### ISSUE TITLE
Mobile rendering terrible

### ISSUE THREAD

**Issue by hut8** [tenex/github-contributions#62]
This looks terrible on mobile devices. Need to fix:

- [x] Make header and hamburger fit inline
- [x] Move search out of hamburger menu
- [x] Make sure that top header part isn't too big (should be fixed by first item) such that it covers page content
- [x] Get footer down to one line
- [x] Kill `Fork me` banner on mobile

**Comment by joshjordan** [comment]
Can we also get the footer down to one line on mobile?

**Comment by hut8** [comment]
Updated

**Comment by joshjordan** [comment]
Might also want to just kill the Fork Me banner on mobile. No one is going to fork it from their phone. Maybe star it from the hamburger menu.
