### ISSUE TITLE
JSON API?

### ISSUE THREAD

**Issue by s2t2** [tenex/github-contributions#80]
Currently I can see my repositories and events on my user page. Would it be agreeable to serve this information in JSON format as well?

#### Repositories:

Current URL: https://githubcontributions.io/user/octocat
Proposed API URL: https://githubcontributions.io/user/octocat.json

#### Events:

Current URL: https://githubcontributions.io/user/octocat/events/1
Proposed API URL: https://githubcontributions.io/user/octocat/events/1.json

**Comment by hut8** [comment]
:+1: 

Try:

* https://githubcontributions.io/api/user/octocat
* https://githubcontributions.io/api/user/octocat/events/1

**Comment by s2t2** [comment]
Yes! Thanks. Sorry if I missed the info about the API. And thanks for your service.

**Comment by s2t2** [comment]
@hut8 Let me know if you would like help documenting the API (in the README.md and/or at https://githubcontributions.io/api/). 

I just wrote a ruby wrapper for it: https://github.com/data-creative/github-contributions-api-ruby

**Comment by hut8** [comment]
@s2t2 wow that's pretty exciting! Thanks so much. A PR that adds your link and/or whatever documentation about the API would be appreciated!
